name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pytest=6.2.2
  - scipy=1.5.2
  - mlflow=1.14.1
  - pip=20.3.3
  - pip:
      - wandb==0.10.21
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components